
/*
 * This source file was generated by the Gradle 'init' task
 */
package aliveBoard;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void appHasAGreeting() {
        GameEntry classUnderTest = new GameEntry(2, 2);
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
